version: "3.9"
services:
  app:
    build: .
    environment:
      - DB_URL=postgresql://postgres:postgres@db:5432/postgres
      - DB_ARGS={}
    ports:
      - 8080:8080
    depends_on:
      - "db"
    command:
      [
        "./wait-for-it.sh",
        "db:5432",
        "--",
        "uvicorn",
        "jqtodobackend.backend:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8080"
      ]
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
