name: CI
on: [push]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.10.2]
        poetry-version: [1.1.13]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies
        run: poetry install
      - name: Verify formatting
        run: poetry run black --check .
      - name: Perform static type checking
        run: poetry run mypy .
      - name: Run tests
        run: poetry run pytest